# This file tells Netlify where your functions live and their settings.
# All function settings are grouped under this single [functions] header.
[functions]
  directory = "netlify/functions/"
  timeout = 25

# This tells Netlify to install the dependencies for your functions.
[build]
  command = "npm install"
