# This tells Netlify to install the dependencies for your functions.
[build]
  command = "npm install"

# This groups all function settings under one header
# and increases the timeout for all functions to 30 seconds.
[functions]
  directory = "netlify/functions/"
  timeout = 30
