# This tells Netlify to install the dependencies for your functions.
[build]
  command = "npm install"

# This sets the directory for all serverless functions.
[functions]
  directory = "netlify/functions/"

# This applies specific settings to ALL functions in the directory.
# Using the wildcard "*" is a more robust way to set global function configurations.
[functions."*"]
  timeout = 30
