# This tells Netlify to install the dependencies for your functions.
[build]
  command = "npm install"

# This sets a specific timeout of 30 seconds ONLY for the 'generate-sbar' function.
# This syntax is more robust and will fix the deployment error.
[functions."generate-sbar"]
  timeout = 30
