# This file tells Netlify where your functions live.
[functions]
  directory = "netlify/functions/"
  # This increases the timeout for all functions to 25 seconds.
  timeout = 25

# This tells Netlify to install the dependencies for your functions.
[build]
  command = "npm install"
  functions = "netlify/functions/"
